### ISSUE TITLE
Unable to install mods contained in folders in 0.9.6

### ISSUE THREAD

**Issue by DCAFOC** [sedenion/OpenModMan#10]
In 0.9.6, mod folders contained in the target's library do not appear in Open Mod Manager. Zip files in the target's library folder appear and are available for install.

Mod folders would appear and be available for installation in 0.9.4.

![image](https://user-images.githubusercontent.com/34700508/124795996-467ffe80-df16-11eb-9932-b20b3089a523.png)

**Comment by sedenion** [comment]
Hi, this is not a bug, this is simply a disabled option. You can enable it again in the Target Location properties parameters, in the menu Edit > Target Location properties... Go the the Library tab, and check the "Developer mode" option.

**Comment by DCAFOC** [comment]
Thank you!
