### ISSUE TITLE
Depedencies can not be removed/edited by the package manger

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#13]
Currently it is not possible to remove dependencies from by using the package manager to edit mod packages. It looks like they are removed by the UI but its not done in the archive on save.

It would also be great that the rightclick menu on a package allows to directly open the selected package in the package manager prefilling the destination for quick edits.

**Comment by sedenion** [comment]
The not properly modified or erased package properties bug is now fixed. I also added ability to load selected package in Package Editor (via menu & shortcut) and implemented destination path prefilling. All will be available the next release.
