### ISSUE TITLE
Install a mod that has depencencies that overlap can cause dialog box that is to large (unclickable)

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#14]
I currently trying to use a mod package (empty) for a racing Championship that uses the dependency system to install/download all required cars and tracks. (like a shared batch) 

The tracks mods packages contain all a readme file that overlaps with the other tracks causing the dialog box to come up if the install should proceed. This is a good thing on regular mod installs, but when you install a mod with many dependencies it causes an issue that the dialog box gets to large. It might be an option to make the install of a package that has dependencies similar to the batch silent install option (At least for the warning of the overlap for the containted dependencies).

The first screen looks good but can also get to large in case a huge depdency list is set up:
![grafik](https://user-images.githubusercontent.com/85709777/147878542-5908eac3-0d01-42a9-9ecc-6c91895bfff3.png)

But the second confirmation dialog for the overlap gets even bigger and contains duplicate entries:
![grafik](https://user-images.githubusercontent.com/85709777/147878728-c09a3cdb-0f63-4919-b159-8d19a2b8e89a.png)

An uninstall+dependencies option including all dependencies would also be a nice option.

**Comment by sedenion** [comment]
I see your point, however, the way these packages are overlapping each other become as toxic as the warning message let it appear. Overlapping not only throw warning, it also build a backup tree to ensure proper file sequential restoration, this is not as trivial as on may think.

As you can see, the search algorithm is looping recursively over each package which result in this huge list, this also mean that backup algorithm is creating backup cross-dependencies (I am even curious to see what exactly happen at this stage).

I am sorry but the good answere here si not to silent the warning, but to manage your packages to not overlapp each other this way, especially if this is only a readme file. If you want to include a readme file in your package, do not put it within the installed files, simply set the description, this will create the proper readme file in the root of the package.

**Comment by retroluxfilm** [comment]
No worries mate. As we need to rework all mod packages anyway to be able to use OMM. It should be possible to remove the readme file and put it into the description instead. (which autogenerates a readme.txt file)

For the message you could use a scrollable textbox inside the message that would keep the dialog window at the same size for example. 

Still an "Uninstall+Dependencies" option that would uninstall the mod including all dependencies would also be a nice option. 

_Note:_ The installation worked flawlessly, even with all the overlapping dependencies. Even marking all packages correctly and uninstalling them all in order. Very nice work btw.  

_Sidenote:_ I am currently working on a quick tutorial/guide to set up the OMM for your first game (with markdown). I read on eagle.ru forum that you would be happy if someone would be doing it. When I am done I can send it over to you in case you want to add it to the wiki.

**Comment by sedenion** [comment]
Unfortunately all dialog message use the built-in WinAPI dialog function that does not allow such customization and I feel a bit lazy to create a new whole custom dialog only for that. So I choosen a simpler and rustical way : cutting the list after 5 lines and adding a mention "and N other package(s)". If there is really a need to create a new dialog for that, I will, but for now I think this simple trick is sufficient.

About the "Uninstall+Dependencies", this is not a trivial feature, it requiere some key new functions that are not currently implemented. I keep the idea, but not for the upcoming release.

**Comment by retroluxfilm** [comment]
I find your current solution good for the dialog message and agre that creating a special dialog just for this case would be wasted effort.

I am looking forward for the extra uninstall option if you decide to implement it.

Here is the first draft for the tutorial and will get some improvement later.
https://vrtoolkit.retrolux.de/omm/omm_quickstart.html
(its currently placed at a temporary github page that uses markdown an jekyl to create a webpage.)

**Comment by retroluxfilm** [comment]
In case you find the tutorial usefull you can find all the files here. https://github.com/retroluxfilm/reshade-vrtoolkit/tree/gh-pages/docs/omm

Feel free to use them as you like.

**Comment by sedenion** [comment]
Thanks, Your Quick Start guide is a bit too specific on some aspect and lack of precision in others, but I will use it as basis to write one.

**Comment by retroluxfilm** [comment]
This ticket can be closed as well. Issue was fixed and suggestions implemented as well. Looking forward for the release of the new version so that the PHP library works (md5hash).
