### ISSUE TITLE
Pressing Delete button while in Package Editor asks to delete the mod that is currently selected in OMM

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#16]
When pressing delete while editing text inside the Package editor and a mod in the library in OMM is selected it will issue to deleted the mod as well from the library. Luckily there comes a message prompt before that so it can be canceled.

**Comment by sedenion** [comment]
Fixed, but for the next release. Actually this is all keyboard shortcuts that still working unless you unselect all package.
