### ISSUE TITLE
Large depedency list ist not fully visible in package properties dialog

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#17]
When many dependencies are used it can not easily be seen which one are added. Using a scrollable textbox like on the description can be helpfull.
![grafik](https://user-images.githubusercontent.com/85709777/149508092-333a92e8-90e9-4817-8519-0171eda99b30.png)

Note: Editing dependencies in the package editor would be great, especially when just a version number has changed.

**Comment by sedenion** [comment]
Fixed, I also reworked the Overlap list to display mods identities when possible.
