### ISSUE TITLE
Suggestion: Differenciate Folder icons easier from Archive icons

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#21]
Currently the icons are very similar in color and form that when preparing packages its difficult to find folder that can be removed or converted to a package.

I also noticed that that there is no error message to the user when a folder could not be deleted as another application has a handle on it. It simply fails silently.

**Comment by sedenion** [comment]
Done for icone. Please open a new issue about the folder delete failing without error.
