### ISSUE TITLE
When there are point before the version suffix it will not detect it correctly

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#24]
When a package is named Like:
AMS.Ferrari.GT1.Challenge.[GTR2 PHYSICS].v1

The version will not get detected when there are points before the version suffix. Removing the points will fix it on the package.

**Comment by sedenion** [comment]
Well, currently only space, - and _ characters are considerated as valid separators for version (to identify the V as not part of a the name). I suppose I can add the dot without risk...

**Comment by retroluxfilm** [comment]
Yeah i dont know why a few modders used points in the package names... but I guess it should work when searchig for the last "_v" of the package name and then try to parse the stuff behind it for the version number.

**Comment by sedenion** [comment]
Added dot as authorized delimiter/separator for version string
