### ISSUE TITLE
Local repository creation not working 0.9.9 (Beta)

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#25]
During testing to create a repository I noticed that it does not work anymore:

![grafik](https://user-images.githubusercontent.com/85709777/154810221-4e1c35d4-f30f-4aaa-9b83-8f1f37117194.png)

**Comment by sedenion** [comment]
That is a very dumb mistake of mine... I inverted the test result... the true is false and the false is true... I think I will cancel the release an Re-Release...

**Comment by retroluxfilm** [comment]
Can happen mate. You could aslo deploy a hotfix version 0.9.9.1 just in case people already have downloaded 0.9.9.

**Comment by sedenion** [comment]
Solved
