### ISSUE TITLE
Package Info block below the library gets invisible 0.9.9

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#26]
When minimizing OMM and reopening the window the package info will not be visible anymore

![grafik](https://user-images.githubusercontent.com/85709777/154810356-d8cb1213-5064-4af8-b722-0544c0f45bde.png)

(Its possible to scale it out again when picking on the lower edge as it is still there but scaled down)

**Comment by sedenion** [comment]
Solved
