### ISSUE TITLE
Package category on remote repositories are not shown in the list 

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#27]
I am not sure if that is an issue that the category tag is differently written to the repository xml as I generated it with the PHP library, like that. Could not test the OMM repository generation as it is currently not working.

```xml
<remote ident="MISC_-_Retrolux_AMS_Reshade_v1.6.0" file="MISC_-_Retrolux_AMS_Reshade_v1.6.0.zip" bytes="10278750" checksum="144f73a554d43728">
      <url>mod_packages/Misc/</url>
      <category>MISC</category>
    </remote>
```

![grafik](https://user-images.githubusercontent.com/85709777/154810620-e90efb8b-60df-4795-9892-62f9c1f4f396.png)

**Comment by sedenion** [comment]
Category must be an attribute, not a child node:
     `<remote ident="blahblah" category="MISC" file="blahblah" bytes="10278750" checksum="144f73a554d43728">`
Should be properly parsed.

**Comment by retroluxfilm** [comment]
oki doki. Fixed it in the PHP library and it works now. Closing issue.
