### ISSUE TITLE
Markdown numbered list issue

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#28]
Currently it seems that the numbered list on markdown are no displayed correctly. It adds additional line changes and extra numbers that are not preset in the text file.

Here is an example how it looks in OMM, the Raw readme and in the Markdown visualization from Rider

![grafik](https://user-images.githubusercontent.com/85709777/154840830-29795f50-a9fb-4e74-8ff1-c1dcf6c997ca.png)

Great feature btw to add markdown support!

**Comment by sedenion** [comment]
I know... The bad news is that I suspect the problem come directly from the Parser, which is thirdparty... But I will investigate this. The workaroud currently is to avoid or do realy care with cariage returns between list items, especialy if cariage returns ar preceded by more than one space.

**Comment by sedenion** [comment]
Well after some investigation I spotted the problem and, good news, this is not the parser... The bad news it that it is  - again - due to RTF format nature, which already gave me some headache for lists render... I have to implement a more robust algorithm.

**Comment by sedenion** [comment]
Problem solved.

**Comment by retroluxfilm** [comment]
I can confirm that the lists now look as they should be. But sadly some other issue came up after the fix:

It now removes the first number on this structure in the changelog versions for example:

![grafik](https://user-images.githubusercontent.com/85709777/154862104-ea35b3b8-cd74-4e5c-bfd4-532f85572569.png)

**Comment by sedenion** [comment]
Solved, a little space for human a big difference for RTF. I did not published a new release but I updated the binary of the last one (0.99.1).

**Comment by sedenion** [comment]
Solved, also solved UTF-8 BOM of loaded source text not properly skipped. Finaly released a second hotfix. Hope this time is the good one.

**Comment by retroluxfilm** [comment]
Now everything looks perfect. Good work mate 👍
