### ISSUE TITLE
Better dependency handling

### ISSUE THREAD

**Issue by jpsearaphim** [sedenion/OpenModMan#29]
The dependency form when creating a package needs to be a bit more advanced in my humble opinion. 
"Identity" alone is a bit unclear, especially when dealing with versioning. I am aware it's simply the "raw" name of the mod package without the extension but I still had to figure it out. I think a better way to handle this would simply be to add a browse button which looks for a properly formatted package file. 

Another thing is to allow a version range. Ex: x_package_v1 depends on y_package >= v1 but < v3. This also hints at being able to handle incompatibilities. If a mod developer is aware that X mod is incompatible they should be able to include that in a list somewhere and the mod manager will resolve those on install.

**Comment by sedenion** [comment]
I agree that dependency list in Package Editor need a better selection mechanism. It is also a need for documentation.  I will think about that.

For the version range, this would need big code refactoring, and specially a new Package definition XML shema. A more reasonable thing can to be let user specify incomplete identity, withou version, in the idea of allowing to match any version of the mod.

**Comment by sedenion** [comment]
Mod-Package editor now allow to add dependency Mod by browsing and selecting Mod file.
