### ISSUE TITLE
Feature: Allow to edit batches

### ISSUE THREAD

**Issue by lorthirk** [sedenion/OpenModMan#3]
Is it just me, or there's no way to edit a batch?

EDIT: I will add some context, since this is probably not the most informative issue in Github :P

First of all, just to clarify, I'm talking about batch content, i.e. which mods are activated or deactivated when running the batch.

The reason I'm asking this is because every time I add a new mod in my collection, the only way to go is to delete all my existing batches and recreate them to include the new mod. With growing numbers it can quickly turn in a boring and error-prone task...

**Comment by sedenion** [comment]
The feature is now implemented, will be available in the next release.
