### ISSUE TITLE
Crash when deleting a folder (legacy/developer mode) from the library through OMM

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#31]
When deleting a folder in the library tab it will crash OMM. (Folder is correctly deleted though)

**Comment by sedenion** [comment]
I am unable to reproduce this on my side. Can you please make further tests, and try to find a more precise condition (via menu or keyboard, presence of subfolders or not, how many, etc)...

**Comment by retroluxfilm** [comment]
I did further tests and it seems that the crash is caused by the auto refresh of the library folder.

Steps to reproduce on my end:
- Create an empty folder "Test123" inside your library directory 
- Open OMM
- Delete the created folder "Test124" from the library directory through the windows explorer.
- OMM crashes

It also happens with a complete empty library without any mods present apart from the newly created folder.

Let me know if I can help further to track it down

**Comment by sedenion** [comment]
There is no problem on my side... I did absolutely no changes in the directory monitoring process, then I suspected the problem may comes from the picture and description scan/load process for folders, but if you tell my this happen even with an empty library this become even more strange. 

I will check the code on my side, on your side, you can download the joined executable, which is a special built version with DEBUG output enabled. You place it beside the OpenModMan.exe file in the installation folder, and you run it via console (either powershell or legacy command prompt), then you reproduce the crash and check the last output lines. You will see no error, but this can tell me aproximately "where" the program stoped.

[OpenModMan_DEBUG.zip](https://github.com/sedenion/OpenModMan/files/8192210/OpenModMan_DEBUG.zip)

**Comment by retroluxfilm** [comment]
This are the last calls when it crashes. 
```
DEBUG => OmUiMgrFootDet::_onShow
DEBUG => OmUiMgrFootOvw::_onShow
DEBUG => OmDialog(ID=700)::_wndproc : WA_INACTIVE
DEBUG => OmUiMgrMainLib::_dirMon_fth (changes)
```

**Comment by sedenion** [comment]
Ok I managed to reproduce the bug, and I think fixed it. This is not specifically related to Developement (Folders) Packages, but to any removed Package if it was the first or the only one of the list. I also fixed a memory leak... Can you try this new version and confirm the bug is fixed ? 

[OpenModMan_DEBUG.zip](https://github.com/sedenion/OpenModMan/files/8192821/OpenModMan_DEBUG.zip)

**Comment by retroluxfilm** [comment]
Your fix works and OMM does not crash anymore. 👍
