### ISSUE TITLE
Destination folder access error

### ISSUE THREAD

**Issue by schradj** [sedenion/OpenModMan#34]
I'm running as administrator.  It appears it does not like a network drive as a destination folder.  Other programs have no issue interacting with this network drive.  Any suggestions?

**Comment by sedenion** [comment]
Right now I have no clue. As I said before, OMM simply performs a permission check against folder according its own process, theoretically, if check fail, this mean the program does not have permission, that's all. However, I never studied the case of network folders, where some negotiation may occure inbetween (typically,  prompt for login as user with password for access)... 

So, I will need some more information to begin investigation and trying to reproduce phenomenum on my side. First, I need some informations about the network folder:

- What kind of "Network Folder" is ti ?
  - Standard Windows local network shared folder
  - Integrated or third-party "Cloud" folder (such as OneDrive, DropBox, etc.)
  - FTP or WebDAV configured access
  - Other...
  
- In case of local shared folder, How access is defined for this folder ?
  - Is it an Anonymous / Guest access (no authorization required) ?
  - Is it a restricted "by user" access, maybe with user/password login prompt ?
  - Tell me everything you can about permission/user access for this shared folder.

Also, you will find (bellow) as attached file a special "DEBUG" build of OMM executable that allow to trace more elements troughh the console. Please download and extract the contained .Exe file in your OMM installation folder, just beside the original .Exe file.

[OpenModMan_DEBUG.zip](https://github.com/sedenion/OpenModMan/files/8618654/OpenModMan_DEBUG.zip)

Once done, you can simply launch the "DEBUG" executable by double-clicking it. You will see that a secondary console window is automatically opened with the OMM window, this is where debug informations appear. Now, go to simply reproduce the access problem and once you see the error message, do not touch anything and read what happened in the console. Near the end you should see something like that: 

```
DEBUG => Om_checkAccess(FILE_ADD_FILE | FILE_ADD_SUBDIRECTORY | FILE_WRITE_DATA | FILE_APPEND_DATA | FILE_WRITE_ATTRIBUTES) : denied, allowed access:
[x]  FILE_READ_DATA + LIST_DIRECTORY
[ ]  FILE_WRITE_DATA + ADD_FILE
[ ]  FILE_APPEND_DATA + ADD_SUBDIRECTORY
[x]  FILE_READ_EA
[ ]  FILE_WRITE_EA
[x]  FILE_EXECUTE + TRAVERSE
[ ]  FILE_DELETE_CHILD
[x]  FILE_READ_ATTRIBUTES
[ ]  FILE_WRITE_ATTRIBUTES
[ ]  DELETE
[x]  READ_CONTROL
[ ]  WRITE_DAC
[ ]  WRITE_OWNER
[x]  SYNCHRONIZE
```
This is the output of the permission check function, and this is what I need. If you don't see any output like this, search for another line that beging with `DEBUG => Om_checkAccess`, this is what is interesting in context.

**Comment by schradj** [comment]
The path is a symbolic link which points to a samba share.  It is restricted by user access.  The samba share on the NAS server is saved as a mapped network drive using saved username/password credentials.
 Ill try to find some time to run your debugger this week

**Comment by schradj** [comment]
[New Text Document.txt](https://github.com/sedenion/OpenModMan/files/8673568/New.Text.Document.txt)

**Comment by schradj** [comment]
did a quick test pointing all the destination folders to local drives and had no errors.  cant fully test since Im still trying to figure out how to define a repo

**Comment by sedenion** [comment]
The log result you give suggest that OMM have absolutely no access to anything, not even folder located in local C: drive, not even for listing content... I will test network shared folders on my side, but at this point I have to tell you that you obviously have folder permission issues, even locally.

**Comment by schradj** [comment]
No I don’t.  OvGME doesn’t have any issues with the same exact folder

**Comment by sedenion** [comment]
Ok, tested on my side and identified the cause of the issue (for network folder at least).

Permissions for **public** (anonymous/guest allowed) network share is properly evaluated. However, **non-public** (user login required) network share permissions cannot be properly evaluated the normal way, precisely because permission rely on specific "network user" login. Proper evaluation would require to prompt for username and password, which is not convenient and would requiere a lot of modifications.

So, for this very specific case, I introduced a bypass, if the path is identified as network path (typically: "\\SomeComputer\folder\"), the denied access is ignored, and considerated as allowed. This also mean that if there is actualy read or write restriction, this would produce some subsequent errors, due to file I/O errors.

You can try using the latest release (0.9.9.8) : https://github.com/sedenion/OpenModMan/releases/tag/0.9.9.8

**Comment by schradj** [comment]
New version appears to have allowed me to link my software context paths to that location.  Reading from that location when using the package editor still throws an error

**Comment by sedenion** [comment]
I tested on my side and everything work fine ( Destination, Library and Backup folder as network share ) as long as you have proper access to theses folders. This may no work if : 

- User that runs OMM did not previously properly logged in to the shared folder: OMM does not implement SMB login mechanism (which is completely different from the usual security management), so the user need to ensure that access to network shares is granted before running OMM.
- OMM is running as a different user than the one that properly logged in to the network shares (which lead to the problem described above), this will happen for example, **if you logged in to network shares using your normal account, but launched OMM as administrator**.
- Supplied path si not detected as network path. For example, a path to shortcut in local drive like "C:\document\My Shortcut" that actually points to a network shares. I don't have tested this case, but reading [Microsoft doc](https://docs.microsoft.com/en-us/windows/win32/api/shlwapi/nf-shlwapi-pathisnetworkpathw#remarks), this would prevent correct detection of network share.
