### ISSUE TITLE
Package Manager Prefill not working in same cases

### ISSUE THREAD

**Issue by retroluxfilm** [sedenion/OpenModMan#35]
I prepared a tutorial video for OMM use and stepped directly into a little bug. It seems that when the package manager was already open at some point it does not prefill the image and description when loading it up again.

Can be seen here in the video:
https://youtu.be/YxUOH7LhZbk?t=1959

**Comment by sedenion** [comment]
Issue identified and solved, also fixed software context not properly selected after creation. Will be available in the next release...

**Comment by retroluxfilm** [comment]
I can confirm that both works now. Good work!
