### ISSUE TITLE
Repository refresh bug

### ISSUE THREAD

**Issue by schradj** [sedenion/OpenModMan#37]
The refresh button on the repository doesn't seem to be fully updating until I completely close and reopen OMM.  If the repo is changed while I have OMM open, old mod packs still appear and ones that have been updated fail on a checksum error.

**Comment by sedenion** [comment]
You right, repositories refresh mechanism lack of consistency, I will work on that.

**Comment by sedenion** [comment]
Fixed in the lastest 1.0.2 release.
