### ISSUE TITLE
How to install all files

### ISSUE THREAD

**Issue by amn2be** [sedenion/OpenModMan#39]
How to install all files regardless of the overwrite of files. I want to install mods Aircraft but it tells me I cannot and overwrites multiple mods. Assistance would be amazing thank you.

**Comment by amn2be** [comment]
Discord Name is RayBurge#6937

**Comment by sedenion** [comment]
In any case, except you cancel operation, all files are installed. The manager only warns you that installed files will overwrite previously modified files. Manager will also create kind of backup dependency tree to keep ability to properly restore initial files. You can disable the warnings in the Target Location's properties.
