### ISSUE TITLE
Updating packages

### ISSUE THREAD

**Issue by schradj** [sedenion/OpenModMan#44]
Currently using 1.0.4

Repo admin has pushed a new version of a livery pack.
I download it and, when prompted if I want to keep the old version, I click 'no'.
Then, in the Packages Library tab, both the old version and the new version are listed but the old version has an X next to it.  When I go to install the new version if says it overlaps and will overwrite a previously installed package and lists the name of the old version of the package.  
I click Continue and the new version appears to install, but the old version is still listed and now has two X's next to it.  I go to delete it and it says the 'Package source does not exist'
Then, if I click 'Uninstall', I get a message indicating that this overlaps with the new version and that the new version will also be uninstalled.
Why doesn't it recognize this as an update and remove the old version from the package list?

**Comment by schradj** [comment]
I suppose evaluation of user interface is always subjective but, when the program seems to recognize it as an update to existing package, but then installs it separately anyways as though it were a entirely different module, leading to file conflicts, this is consistently causing confusion for the users in my community whom I dragged kicking and screaming from OvGME to OMM.  If the program recognizes it as an update (which it does from the yellow star icon next to the current listing), it would seem like a more logical behavior to just update that module for the user instead of forcing the user to manually uninstall the old version and then install the new version.

**Comment by sedenion** [comment]
I know this is confusing, this is one of the behavior inducted by the "let to user the choice" philosophy, since this is technically possible... I will though about an option to "forbid" multiple version of the same package so to make everything more consistant an understandable for the most common usage.

**Comment by sedenion** [comment]
So, I made a new release that fix a critical bug and forces package to uninstall if it is deleted during upgrade process. This will avoid such confusion situation. To be sure the older package will be removed (either renamed or moved to trash) click the "Upgrade" button/menu instead the "Download".

**Comment by sedenion** [comment]
Finaly I changed the default behavior for download... see the new 1.0.6 version:
https://github.com/sedenion/OpenModMan/releases/tag/1.0.6
