### ISSUE TITLE
Suggestion: Exclude hidden directories/files

### ISSUE THREAD

**Issue by chump29** [sedenion/OpenModMan#45]
Currently, OpenModMan displays hidden directories/files. Are there future plans to exclude these from displaying in the list of packages? I currently use a setup that has a hidden __working_ directory within the Custom Library Folder.

**Comment by sedenion** [comment]
Option will be available in the next release. Default setup will be to exclude hidden file, the parameter will be available in the Target Location Properties Library tab.
