### ISSUE TITLE
Crash after download of updated repository package 

### ISSUE THREAD

**Issue by fizzle77** [sedenion/OpenModMan#47]
Every time I download an updated repository package, OMM crashes. I have squadron mates who have reported the same behavior, so I don't think it's something peculiar to my setup.

Some more details:
- This is using the new default "download" introduced in (I think) 1.0.6, which reportedly should do an upgrade of the old package.
- The package does show the upgrade (upward arrow) icon, so it seems to have the correct state.
- Immediately after the download is complete, OMM crashes. 
- Uninstalling the old package first doesn't change the behavior.
- The upgraded package is referenced in a number of install scripts.
- Fixing requires removing the old package, installing the new one, then fixing all relevant install scripts to reference the new one.

Let me know if there's additional details I can gather to help troubleshoot.

Related to #44

**Comment by fizzle77** [comment]
This happens every time, and the package is not correctly replaced. The download succeeds correctly but nothing else happens. The older version remains, side-by-side with the new one. I have to manually remove it and replace it with the new version.

**Comment by sedenion** [comment]
Bug found and fixed, Install scripts sychronization implemented. New version available for download.
