### ISSUE TITLE
Regarding The Project Change

### ISSUE THREAD

**Issue by HDark15** [sedenion/OpenModMan#50]
Sorry if you already know about this. I know you have a concern with 2FA, but someone said something that I agree with.

> TOTP 2FA actually eliminates the need to give sites your phone number because it does the same thing, only shitty sites like google require SMS 2FA as a fallback before they let you add TOTP because they outright don't trust their own standards, see: the go programming language, recaptcha, the living HTML standard, etc.

>With any non-shit FOSS authenticator app like aegis, you can backup your keys in plaintext if you want and keep those wherever you want.
You're also not required to use a phone app, you can take the shared TOTP secrets and generate keys with desktop software or even from the terminal with oathtool, it's so simple, it's just hashing your secret key plus the current time, anything with a CPU can generate codes for you. 

Personally, I use KeePassXC for pass, OTP and backup code.

For GitHub alternatives, I suggest to use https://codeberg.org or https://about.gitea.com/, but I prefer Codeberg. Pls don't use Sourceforge as the main, thank you.

**Comment by sedenion** [comment]
Thanks for comment

Yes I read this "TOTP" thing... Currently almost all TOTP applications are Mobile Phone applications, what a surprise ! Why the hell theses applications have to be installed on my mobile phone ? What a good question... Anyway, I found one TOTP software as browser plug-in but it did not convinced me. 
If you know an Open Source TOTP software that run both on Linux and Windows, easy to use, and that don't requiere I supply any personal information, I will look at it.

Thanks for GitHub alternatives, I will check that. I don't like SourceForge much, too rusktical.

**Comment by kaltokri** [comment]
Take a look at Yubikeys. A cheap blue FIDO2 key is more secure then TOTP and you don't need an app. Also the key does not contain any personal data. I love it. :)

**Comment by Skarafaz** [comment]
Are you seriuos guys? Really? xD

**Comment by sedenion** [comment]
Yes I am seriously pissed off GAFAM force me to use a third-party software and extra procedures to authenticate to their platforms pretending this is for *our security*...
