### ISSUE TITLE
BUG: Afer Install/Uninstall Launch (scripts) button is active. but there no scripts added

### ISSUE THREAD

**Issue by lmiol** [sedenion/OpenModMan#54]
Precondition: 0 scripts created, 1 mod added to lib
1 Press Install Button
Actual Result: Launch button is active
Expected Result: Launch button is inactive (because no scripts added)

Same problem with Uninstall button

**Comment by sedenion** [comment]
The next version will have totally rewritten back end UI logic (it is already totally redone in sources) with most bug like that resolved but maybe with new that doesn't currently exists. Wait for the next 1.2 release to repport such kind of bugs.

**Comment by lmiol** [comment]
when 1.2 build may be available for download (approximately)?

**Comment by sedenion** [comment]
I hope before Christmas, otherwise, soon after
