### ISSUE TITLE
Issues with mod uninstall

### ISSUE THREAD

**Issue by LeviBuerki** [sedenion/OpenModMan#56]
Hello,
I'm having trouble, that whenever I want to uninstall a mod, it does not delete the files in the game folder.

Thank you for your work and let me know if I can be of assistance!

**Comment by sedenion** [comment]
Du you have error/warning message, either via dialog box or in the debug log (menu Help > Debug log) ? Do you have the problem with only one Mod or all Mods ?

**Comment by LeviBuerki** [comment]
Currently all mods, exept if I add a new one, that one works until I restart OMM. I dont get an error, the files just dont get deletet. 
![image](https://github.com/sedenion/OpenModMan/assets/74985872/3d795fdf-857a-49f1-ac91-9655a88e8c3a)
In the screenshot the 25 Squadron should have deleted the A-10CII folder but it didnt.

**Comment by sedenion** [comment]
Ok, bug found and fixed internally. I will publish a new release with this fix, thanks for report.

**Comment by LeviBuerki** [comment]
Great! Thank you very much!
