### ISSUE TITLE
Download throttling

### ISSUE THREAD

**Issue by gcask** [sedenion/OpenModMan#58]
OMM is almost too efficient for its own good: when downloading many packages from GDrive, Google will lock you out.
It's likely you may hit the same results with other providers.

It would be nice if OMM had a download limiter to avoid running into those issues.

**Comment by sedenion** [comment]
hem... what kind of limiter ? download rate ? download count ?

**Comment by gcask** [comment]
Yes: max concurrent downloads and rate limiter are both pretty standard and good options!

**Comment by sedenion** [comment]
Ok I understand now. This is normal, the description is, by design, no more displayed in the Mod properties, that is as simple as this...

**Comment by sedenion** [comment]
feature is implemented internally, will be available in the next release

**Comment by gcask** [comment]
Great! Many thanks, looking forward to it!
