### ISSUE TITLE
No 'description' in the Mod properties window.

### ISSUE THREAD

**Issue by gcask** [sedenion/OpenModMan#59]
When doing right click > Properties on a Mod, the description text is nowhere.

It also doesn't appear in the Mod Properties tab at the bottom.

**Comment by sedenion** [comment]
did the Mod actually have a description in its package, if yes, what type ? Can you provide link to download mod ?

**Comment by gcask** [comment]
It does, it shows up in the Mod Overview tab just fine.
There's just nothing displaying the description in the Properties window, which seems odd.

here's an example one if you need: https://drive.google.com/file/d/1gNktbLNceplsGGt-4j1T8cXEODvRfnhc/view?usp=drive_link

**Comment by sedenion** [comment]
Ok I understand now. This is normal, the description is, by design, no more displayed in the Mod properties, that is as simple as this...
