### ISSUE TITLE
Feature: Allow editing package details

### ISSUE THREAD

**Issue by lorthirk** [sedenion/OpenModMan#6]
It would be great if we could also edit package details not only when creating a package but also at later time

**Comment by sedenion** [comment]
Currently, the only details which could be edited would be the Name, Snapshot and Description.

For Snapshot and Description: 
This require to temporarly unpack then repack the entire zip file with modified files and content, which is the same as creating a whole new package. This is not a trivial operation, especially with heavy content, it is better to avoid it.

For Name: 
Package name is directely related to its file name. Modifying a file name within the Library folder require  - and automatically trigger through an independant thread -  rebuilding of package list with new objects, which implie new memory adressing (new pointers).
This will result that the opened "Package properties" dialog - from where you modified the name - will sudently be related to a logial object that will no longer exists, embeding a pointer to an invalid memory adress, and here, a whole new univers with multiple dimensions of problems will emerge, something like "trying to divid by zero"...

So, to be short: Sorry but for now I will not allow any Package detail modification through the Package Properties...
