### ISSUE TITLE
Cannot set the per-thread max rate to anything over 32767 KB/s

### ISSUE THREAD

**Issue by gcask** [sedenion/OpenModMan#61]
I wanted to limit my download to 1 concurrent download and half my bandwidth (about 50 MB/s), and I am unable to do so: the max rate reset to 10KB/s (lol) when I hit Apply.

**Comment by sedenion** [comment]
Strange, I cannot reproduce on my side... what value did you enter in max rate  ?

**Comment by sedenion** [comment]
Oh, ok I see the title now... indeed, you cannot enter a value greater than 32767... I admin I had left the Win32 API 16bits limitation, thinking 32 Mo/s will be sufficient for a "limit"...

**Comment by gcask** [comment]
Not when you're on fiber - about 125 MB/s uncapped...

It's definitely not a top priority item, just letting you know.

**Comment by sedenion** [comment]
Ok, I switched spin control to 32 bits range, and set 999999 KB/s max.... hope this will be sufficient for the next 10 years. Will be for the next release.
