### ISSUE TITLE
No warning when installing overlapping mods on top of each other

### ISSUE THREAD

**Issue by OR-WS** [sedenion/OpenModMan#64]
Per the title. I have the warning setting enabled in the channel's setting but I'm not receiving a warning.

**Comment by sedenion** [comment]
Hi, sorry for the late response. 
What I found is that the overlaps test and warning work properly, however, I found a small difference between how Packaged Mods and Directory Mods are parsed which can cause overlapp to be not detected in the case the tested Mod is a Packaged version while the the other is not or vice versa. 
Can you confirm that this is what happen to you ?

**Comment by OR-WS** [comment]
> Hi, sorry for the late response. What I found is that the overlaps test and warning work properly, however, I found a small difference between how Packaged Mods and Directory Mods are parsed which can cause overlapp to be not detected in the case the tested Mod is a Packaged version while the the other is not or vice versa. Can you confirm that this is what happen to you ?

Correct. It's happening to directory mods (those ported over from using OvGME).
