### ISSUE TITLE
Presets toggle state of all selected packages

### ISSUE THREAD

**Issue by fizzle77** [sedenion/OpenModMan#65]
In 1.2.3, selecting a preset will toggle the installed state for any mods listed in the preset, rather than installing them.

Example:

Preset A includes:
Mod 1
Mod 2

Preset B includes:
Mod 2
Mod 3

Starting from an empty install, running Preset A works as expected, with Mod 1 and Mod 2 installed.

Now run Preset B.
Exepected: Mod 1 uninstalled, Mods 2 and 3 installed.
Actual: Mods 1 and  2 uninstalled, Mod 3 installed.

The mods referenced have their states toggled, rather than uninstalled any mods not referenced and installing (or leaving installed) mods that are referenced.

A much simpler test: run Preset A, then run it again. On the second run, I'd expect nothing to happen. Instead, all mods are uninstalled.

**Comment by sedenion** [comment]
Bug spotted, will be fixed in the next release. Thanks for report.

**Comment by fizzle77** [comment]
Fix works for me.
