### ISSUE TITLE
Preset migration from 1.1.x to 1.2.x leaves presets empty

### ISSUE THREAD

**Issue by fizzle77** [sedenion/OpenModMan#66]
The presets made it through, but they're all empty and have to be recreated.

**Comment by sedenion** [comment]
I didn't do a test again, at fisrt glance I can't figure out where the bug lie...

When you say empty, you mean XML files are actually empty (no data), or you simply saw that there were no more mods in the install list ?

**Comment by fizzle77** [comment]
No mods in the install list. I've fixed them all, now, so I can't say for sure the state of the XML files right after the upgrade.
