### ISSUE TITLE
Feature request : release in self contained archive without installer (executable)

### ISSUE THREAD

**Issue by Migow50** [sedenion/OpenModMan#67]
hello , is it possible to release software executable in self contained archive without installer 
i would like a lot
thanks my regards

**Comment by sedenion** [comment]
I can provide a kind of "portable" version, with required stuff in an archive file, but not a "self-contained" archive since OMM need some extra DLLs near executable to run. You can create this "portable" version yourself from the installed files, why exactly do you want that ?

**Comment by Migow50** [comment]
yes i mean a portable version i prefer to avoid installer in general thx if you can :) for some reason i can't access the installer archive unlike some installer i wonder why

**Comment by sedenion** [comment]
The "problem" (not an big one) is that the "portable" version will still use user's AppData folder to store its configuration...

**Comment by Migow50** [comment]
it is "ok"  :)
also on another subject do you plan on adding ability  to compile on VC++ ?

**Comment by sedenion** [comment]
No plan for VC++, anyway it should compile on any compiler, the problem is IDE project integration...

**Comment by sedenion** [comment]
I added portables versions in the release assets
https://github.com/sedenion/OpenModMan/releases/edit/1.2.4
