### ISSUE TITLE
Repo Default Files Download Link does not allow pointing at other servers

### ISSUE THREAD

**Issue by TaeruAlethea** [sedenion/OpenModMan#69]
We have a space constrained web hosting situation. We host larger mod files on a dedicated server. With OVGME, We were able to host the XML on the webserver and the Mods on a Data server. When trying to put a URL or IP address into the "Default Files Download Link" box, it would always 404 when attempting to download.

**Comment by sedenion** [comment]
Contrary to what the label suggest, currently, the Default Download Link must be relative path from XML location... It does not support full URL. For now, you can workaround this by setting a custom URL for each file (if you set an URL prefix the filename will automatically be added)

**Comment by TaeruAlethea** [comment]
What do you mean by URL prefix? If we put a URL into the custom URL box and it doesn't have a file extension, it'll assume its the file name, correct?

We host about 20 to 30 mods, so adding a custom URL for each seems like it could be rather tedious.

**Comment by TaeruAlethea** [comment]
Figured it out.
A spot to add File repo url or a way to bulk add a URL to the packages would be appreciated.
