### ISSUE TITLE
Secondary sort by Name when sorting by Status

### ISSUE THREAD

**Issue by shovas** [sedenion/OpenModMan#71]
Would be nice to secondary sort on Name when sorting by Status

When you click the Status field to get it to sort by Enabled it correctly sorts that field but for the Disabled rows they don't seem to be in a particular sorting order

![image](https://github.com/sedenion/OpenModMan/assets/429805/4b66cfca-86cd-4610-b29b-fa1fdc19ddef)

**Comment by sedenion** [comment]
If you first sort by name, then sort by status, did you have the result you expect ?

**Comment by shovas** [comment]
No, unfortunately, after the enabled items I can't tell what order it may be in, it's definitely not alphabetical like when you manually order by Name

**Comment by sedenion** [comment]
fixed in source code, will be effective in the next release.
