### ISSUE TITLE
Ability to resize Channel/Target area vertically

### ISSUE THREAD

**Issue by shovas** [sedenion/OpenModMan#72]
I'd like to be able to expand the Channel/Target area vertically

![image](https://github.com/sedenion/OpenModMan/assets/429805/dd94ca57-38de-40a1-81b3-13bfbf9c999d)

**Comment by sedenion** [comment]
I will consider the feature, but the fact is that such thing is much more complex to implement than it appear...

**Comment by shovas** [comment]
Thanks for considering

**Comment by ssheddan** [comment]
+1

I'm just adding my vote to OP's. It'd be nice to have, but I understand that it isn't so easy to implement.

**Comment by lmiol** [comment]
yeah, why not =)
and if you will make this i think app should save height and after restart app it would be same

**Comment by sedenion** [comment]
Feature implemented in source code, will be available in the next release.

**Comment by shovas** [comment]
Nice, thank you!
