### ISSUE TITLE
Wrong preview after tab switch

### ISSUE THREAD

**Issue by lmiol** [sedenion/OpenModMan#79]
Select is not reset after changing tabs. Because of this, the preview is not updated
https://github.com/sedenion/OpenModMan/assets/264879/f3f753f9-835a-49ff-9a99-948a0c654c52

it is necessary to update the preview from the selected mod

or it is necessary to reset the selection when switching tabs (which seems easier to do)

App version 1.2.7

**Comment by sedenion** [comment]
Thanks, corrected in source code. It would have been nice if reported before today's release... well, this will be for the next one.

**Comment by lmiol** [comment]
how to contact you? i need to text with you.
message me here aleksandr.podaruev@gmail.com
