### ISSUE TITLE
Zip file error when creating a package ?

### ISSUE THREAD

**Issue by speed-of-heat** [sedenion/OpenModMan#8]
I can't get this to work at all, having created a context, and i then create a package i always get the following error message?
![OMM](https://user-images.githubusercontent.com/64099136/115107514-371a9600-9f63-11eb-9359-877fe8cb5483.png)

**Comment by sedenion** [comment]
This is probably some folder permission problem, without more details I can't help more.

**Comment by speed-of-heat** [comment]
what additional details do you need?

**Comment by speed-of-heat** [comment]
i found what the issue was, i think, when you add the package, The destination file name is not populated, i, if you click save as the correct path is populated, if  you enter just the file name it fails , my guess isits trying to save "somewhere" else.

Can we get the destination file to populate as you create the package ? e.g. once you have chosen the package content.

**Comment by sedenion** [comment]
Ok, I think I understand. You entered the destination file name manually without selecting a path by clicking the "Save as..." button, This result an incorrect destination path. 

Anyway the label "Destination file name" is confusing and the program should checks the path is valid before trying to write the file.

I will work on that. For now, know that you MUST enter a valid full path (eg. "D:\path\for\file.zip") in the "Destination file name" entry, either by using the "Save as..." button or by writing it directly. You also can select a valid path using "Save as..." then subsequently edit the file name in the entry.

**Comment by speed-of-heat** [comment]
yes that is correct; thanks!

**Comment by sedenion** [comment]
The Package editor dialog window was reworked, this issue is now fixed by the way
