### ISSUE TITLE
Bug report: Package upgrade breaks on upgradeReplace.

### ISSUE THREAD

**Issue by PraetorAugustus** [sedenion/OpenModMan#81]
Steps to reproduce:
1. Query network repository.
2. Double click updated file (e.g., v1.1 to v1.2).

The new package downloads just fine, but it fails when it tries to replace the old one.

![Screenshot 2024-04-20 144523](https://github.com/sedenion/OpenModMan/assets/4621974/5c732c47-cc7b-4a6d-a92a-3842f0525e8f)

The debug log is sparse, but here's mine:

`[14:25:43]   Manager.openHub: E:\Dropbox\Documents\DCS\OpenModMan\DCS Open Beta\hub.omx`
`[14:25:43]   ModHub[DCS World].ModChan[ION's F-14 Mixtapes].open: OK`
`[14:25:43]   ModHub[DCS World].ModChan[Personal Mods].open: OK`
`[14:25:43]   ModHub[DCS World].ModChan[Stingrays Mods].open: OK`
`[14:25:43]   ModHub[DCS World].ModChan[Testing].open: OK`
`[14:25:43]   ModHub[DCS World].open: OK`
`[14:25:43]   Manager.init: OK`
`[14:45:09]   ModHub[DCS World].ModChan[Testing].ModPack[Spitfire_LF_Mk_IX_Kneeboards_v1.0.4].restoreData: done in 0.02s`
`[14:45:09] X ModHub[DCS World].ModChan[Testing].NetPack[Spitfire_LF_Mk_IX_Kneeboards_v1.0.5].upgradeReplace`

I can (re)install the upgrade package from the Local Library tab, so it's an annoying bug rather than a showstopper.

Let me know if you need more details or want a beta tester.

EDIT: Also, please let me know if this is an ID10T error, a stupid user trick. I tried a couple of workarounds but still had the error.

**Comment by sedenion** [comment]
Can you please give the the repository address/coords so I can test with this specific mod ?

**Comment by PraetorAugustus** [comment]
Of course! And thanks.

address: `http://fightinstingrays.com/mods/`
name: `test`

I had a brainwave this morning and tried it with .ozp archives (I normally use .zip). Sadly, that didn't work either.

Let me know if I can help from my end.

**Comment by PraetorAugustus** [comment]
I found the problem!

I use a custom directory for the Mod Library. The upgrade breaks if I do.

![image](https://github.com/sedenion/OpenModMan/assets/4621974/42851c43-cbd2-4670-a804-0c1f7a738e96)

When I uncheck the custom directory and use the default, upgrades work as intended.

Hope it's an easy fix.

**Comment by sedenion** [comment]
The repository coords you provided doesn't work on my side...

Can you please try using Custom path that doesn't include Tilde (~) in its name ? I also suspect problem with Read/Write permissions.

**Comment by PraetorAugustus** [comment]
Our web server was down overnight. It's back up. The repo should be working now.

Unfortunately, a normal Custom path fails too.

![image](https://github.com/sedenion/OpenModMan/assets/4621974/0d9f0e27-1c96-417a-bff5-f4b7d0cdf9b3)

Read/Write permissions on my end are all default Windows 11. The default folder works just fine, and it has the same permissions as the custom one.

**Comment by sedenion** [comment]
Ok, bug found, fixed in source code, will be fixed in the next release

**Comment by PraetorAugustus** [comment]
Merci beaucoup!
