### ISSUE TITLE
Can't saves repository in .xml

### ISSUE THREAD

**Issue by Tomy105** [sedenion/OpenModMan#82]
1rst post on Github, and not an experience OMM user, so sorry If its a me problem but : when I want to save my repository in .xml , its saves its in .omx  :) 

I have to manually change it to .xml :D 

![test](https://github.com/sedenion/OpenModMan/assets/170878904/1e5c7003-cc43-4cb2-a983-b29889dd43b3)

**Comment by sedenion** [comment]
Fixed in source code, it will be effective in the next release. Thanks for report.
