### ISSUE TITLE
Request :  larger repository list, right click option, repository mismatch

### ISSUE THREAD

**Issue by Tomy105** [sedenion/OpenModMan#83]
Hey !  :) 

I have 3 things to share : 

1) When I query a repo, the list of files below updates, but when I query another repo, the list just add the files on the list, It doesnt switch from on repo to another. Is that a bug ? It could be nice to be able to "disable" a repository
![repo](https://github.com/sedenion/OpenModMan/assets/170878904/d8054128-54dc-4447-8148-ed205c9f2736)

2) Would it be possible to increase the width of the repo list ? Just 3 to be displayed is a bit short. 
![Untitled](https://github.com/sedenion/OpenModMan/assets/170878904/20c4e201-ca24-466b-9138-8cbec67beffe)

3) Also, could it be possible to add a right click option on the repository " download all mods " and / or " install /uninstall " ? 
![down](https://github.com/sedenion/OpenModMan/assets/170878904/841ae737-4958-4a37-a368-85cccb86cd0f)

**Comment by lmiol** [comment]
2 i think it is should not increase spaceб but add to ability to increase manually
3 "download all" is awesome idea

**Comment by Tomy105** [comment]
> 2 i think it is should not increase space, but add to ability to increase manually

Or even better : space self size depending of the quantity of repository ?  :D If set manually, it should remind the configuration after exit  :)

**Comment by sedenion** [comment]
Repository list resizing (and autosave) implemented in source code, will be available in the next release.

**Comment by sedenion** [comment]
I close this issue. You can create new issue for other individual feature request if you want (please only one feature/bug per issue).
