### ISSUE TITLE
[BUG] Add dependencies to mod itself crash an app

### ISSUE THREAD

**Issue by lmiol** [sedenion/OpenModMan#91]
i didn't record crash because it need to wait, first app freezes then after awhile it crashing
https://github.com/sedenion/OpenModMan/assets/264879/6baee610-512d-4173-a44a-213b635e709f

I don't really know what expected result be write
i think after file adding should be alert "You cannot add dependent mod to itself)

**Comment by sedenion** [comment]
Problem solved in source code, also added error message in ModPack editor
