### ISSUE TITLE
[BUG] App crashes after deletion of last repo

### ISSUE THREAD

**Issue by lmiol** [sedenion/OpenModMan#95]
probably you already fixed this one [here](https://github.com/sedenion/OpenModMan/issues/79), but i am not sure so here is another
1 add only 1 repo
2 load files from repo
3 delete repo
4 click on files
AR: app crashes 
ER: i think files must dissapears after repo deletion

https://github.com/sedenion/OpenModMan/assets/264879/0e25c96e-8ad7-4d8f-9192-a2be931817f0

Reproduced on 1.2.7 (1.2.8 reproduced too)

**Comment by sedenion** [comment]
Fixed in source code
